--- # ---------------------------------------------------------------------------
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: vlbc.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Manufacturer
  # ---------------------------------------------------------------------------
  - Name: Manufacturer
    Domain: manufacturer.vlbc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Dealer
  # ---------------------------------------------------------------------------
  - Name: Dealer
    Domain: dealer.vlbc.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Insurance Agency
  # ---------------------------------------------------------------------------
  - Name: Insurer
    Domain: insurer.vlbc.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Registration Authority
  # ---------------------------------------------------------------------------
  - Name: RTO
    Domain: rto.vlbc.com
    Template:
      Count: 1
    Users:
      Count: 1
    
